---
# tasks file for httpdserver
 - name: install httpd
   package:
            name: httpd
            state: present
 - name: copy code
   get_url:
            url: https://raw.githubusercontent.com/uditagarwal1305/ansible_task2/main/index.html
            dest: "/var/www/html/index.html"
 - name: start httpd
   service:
            name: httpd
            state: started
